### ISSUE TITLE
WHERE THE F*** IS THE HTML FOLDER?!

### ISSUE THREAD

**Issue by arionf** [tbleicher/sketchup-react-demo#1]
WHERE THE F*** IS THE HTML FOLDER?!
WHERE THE F*** IS THE HTML FOLDER?!
WHERE THE F*** IS THE HTML FOLDER?!
WHERE THE F*** IS THE HTML FOLDER?!
WHERE THE F*** IS THE HTML FOLDER?!
WHERE THE F*** IS THE HTML FOLDER?!

**Comment by tbleicher** [comment]
https://tbleicher.github.io/sketchup-react-demo/structure.html

**Comment by arionf** [comment]
The zip files that are available in the following path does not contain html, static, css and media folder. Please upload an example of the extension (final working version or .rbz file).

https://github.com/tbleicher/sketchup-react-demo/zipball/master

**Comment by tbleicher** [comment]
Sorry for the confusion. This is not a ready-to-deploy extension but a demo project for SketchUp extension developers. To create a working extension, you have to follow the installation instructions in the README file.

After the final `yarn run deploy:local` the extension will be installed in the Plugins folder of your SketchUp 2017 installation. From there you can copy the `sketchup-react-demo` folder and the `sketchup-react-demo.rb` file and wrap them up as an `*.rbz` or just copy them directly to another machine or SketchUp installation.

**Comment by arionf** [comment]
Please upload the ready-to-deploy or *.rbz if you have already did it. Thanks

**Comment by tbleicher** [comment]
Sorry. I have no intention of providing an extension file based on this
code. I have not done any quality checks on the Ruby code and it could
damage your SketchUp projects.

If you are a developer you have enough to go on. If you are not, then this
is not for you.
